# Generated by Django 3.0 on 2020-08-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200807_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
