# Generated by Django 3.0 on 2020-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_mango'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Current Events', 'Current Events'), ('Advice', 'Advice'), ('Pets', 'Pets'), ('Books', 'Books'), ('Movies / TV', 'Movies / TV')], default='General', max_length=25),
        ),
    ]
